# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec12fe1357054fde8506418eaf135960ad8bed3368349893a95f83ebc23f85e4d7b8eae5758481e2de25e6f14f0b6d820b19f1df0e59cdd2776dd3da1bf7cb16

test:
  secret_key_base: bc705292b8402189c2d01b1ba6547093c4b1f6b4ddb1de729292c904bd4dd43547514727c26c21e5a098839065590829ef1fe3e6010e284a0e8780d39451a54c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
